### ISSUE TITLE
Add option to disable background discovery

### ISSUE THREAD

**Issue by lathanh** [codebutler/farebot#102]
If an NFC card is stored next to the phone, then any time the phone is turned on this app is opened (even if, say, the phone was unlocked for an email notification). This is an annoyance when scanning a card isn't the intent. Please add an option to ignore tag discoveries while the app isn't open.

**Comment by micolous** [comment]
I believe this error report is invalid.

Options > Launch from background > untick

**Comment by lathanh** [comment]
The version in the Google Play store doesn't have this feature.
