### ISSUE TITLE
Opening APK from Google Inbox mysteriously triggers Farebot intent

### ISSUE THREAD

**Issue by treelzebub** [codebutler/farebot#108]
Reproduce:
0) Farebot is installed
1) Receive an APK in an email attachment
2) In Google Inbox, tap attachment to download/open

Weirdness: Farebot opens up the "Add a Card" dialog, and triggers the OS to request enabling NFC

This is especially strange because the gmail app will download/install APKs normally, while Inbox does not. It does not appear to be a Default App issue, either, as opening from Downloads or a file browser will install the APK per usual.

Attached: 1 screen from Inbox, and 2 resulting screens from Farebot
![screenshot_2015-07-24-17-00-28](https://cloud.githubusercontent.com/assets/7496900/8887018/df97bb54-3228-11e5-9a8c-9d45968ec910.png)
![screenshot_2015-07-24-17-00-36](https://cloud.githubusercontent.com/assets/7496900/8887019/df98ac3a-3228-11e5-8f78-9656df996d91.png)
![screenshot_2015-07-24-17-00-41](https://cloud.githubusercontent.com/assets/7496900/8887017/df96f034-3228-11e5-86db-b75b1908ba88.png)

**Comment by codebutler** [comment]
This is fixed in the upcoming release.
