### ISSUE TITLE
Support Kiev metro cards

### ISSUE THREAD

**Issue by vzaliva** [codebutler/farebot#121]
Kiev metro cards are physically compatible with FareBot but it could not decode their contents.
Here is a link to an article (in Russian) which describes with details revere-engineered card protocol and python code snipped to read the card:

https://habrahabr.ru/post/141213/

**Comment by phcoder** [comment]
@vzaliva Could you send me a card? I'll pay for the shipping and the card

**Comment by vzaliva** [comment]
If you are in US, I can send you my card. If you are in Europe, it is better to find somebody closer to you to send one.

**Comment by phcoder** [comment]
I'm likely to travel to US next month. Which region are you in? Bay Area by any chance?

**Comment by vzaliva** [comment]
I am in bay area (Saratoga, CA).

**Comment by phcoder** [comment]
I got my hands on 2 cards: pre-2016 and post-2016. Later one are MiFare Plus S operating in SL3 mode without any open sectors. So until vulnerability is found we can't read post-2016 cards. Pre-2016 cards can be implemented but I'm not sure it's worth the time

**Comment by vzaliva** [comment]
If newer cards are not readable there is not much point to support old ones.
Besides, as now Kiev metro supports both google and apple pay I personally stopped using cards :)
