### ISSUE TITLE
 "Attempt to invoke virtual method 'short android.os.Bundle.getShort(java.lang.String)' on a null object reference"

### ISSUE THREAD

**Issue by emveeha** [codebutler/farebot#148]
The card is  an OV-chipkaart scanned by an oneplus 5 running stock android N.

Logcat:
https://pastebin.com/Jzd5Nwb8

Looks like the same issue here:
https://github.com/codebutler/farebot/issues/97

**Comment by codebutler** [comment]
It looks like you somehow have an invalid key saved. Does this still happen if you remove/re-install the app?

**Comment by emveeha** [comment]
Yes, I did remove/re-install the app. Seems like the problem is device specific:
https://github.com/micolous/metrodroid/issues/31

**Comment by codebutler** [comment]
Doesn't look like there's much I can do here, sorry 😞. Please let me know if you see this on other devices.
