### ISSUE TITLE
Not working Pixel 2 XL

### ISSUE THREAD

**Issue by bdwyer2** [codebutler/farebot#160]
Farebot does not do anything on my Pixel 2 XL when I place a clipper card in front of the NFC sensor with the app open.

**Comment by gaul** [comment]
I have the same problem with a Clipper card using a Pixel 2 running Android 8.1.0.

**Comment by phcoder** [comment]
I tested with both Farebot and Metrodroid with Pixel2. Both work. Is your NFC enabled?

**Comment by gaul** [comment]
Tested again with Android 9.0.0 and Pixel 2 works.

**Comment by bdwyer2** [comment]
@gaul still not working for me with a clipper card. Are you on the Pixel 2 or Pixel 2 XL?

**Comment by gaul** [comment]
@bdwyer2 I tested with a Pixel 2, not XL.
