### ISSUE TITLE
BART trips showed on incorrect dates

### ISSUE THREAD

**Issue by theimmc** [codebutler/farebot#39]
I took 4 trips on 2 separate days within a month. All 4 trips show up on the same date. This is always the later date. Attaching screenshot. Will try to attach the card data as well.

![Screenshot_2013-03-18-17-18-16](https://f.cloud.github.com/assets/3904575/273666/d4daef0e-902e-11e2-947a-e11e56b8b601.png)

**Comment by codebutler** [comment]
Please download the latest version from Google Play and open a new ticket if you're still having trouble.
