### ISSUE TITLE
Key import from Farebot

### ISSUE THREAD

**Issue by mrvanes** [codebutler/farebot#42]
The key import process in Farebot is quite awkward. You need to mail yoursefl a .farebotkeys file and hope the mailclient offers farebot as a handler (which the default imap client doesn't!). It would be nice to have a import button on the keys dialog that could be pointed to a keyfile location on the device, after which a recent existing scan could be mapped to this (without having to rescan the card). Using a recent "raw" scan is more intuitive than having to scan the card again.

**Comment by codebutler** [comment]
The upcoming release allows you to browse for a file.
