### ISSUE TITLE
Reverse sorting of trips

### ISSUE THREAD

**Issue by mrvanes** [codebutler/farebot#43]
It would be nice to have the most recent trips sorted on top.

**Comment by codebutler** [comment]
What type of card is showing older trips first? most recent trips first is the intended behavior.

**Comment by mrvanes** [comment]
Pfff... this has been a while. Will try  upcoming version and report back since I've had NFC problems with recent phone(s). Might have to recalculate keys since card was replaced since then as well.

**Comment by codebutler** [comment]
Please download the latest version from Google Play and open a new ticket if you're still having trouble.
