### ISSUE TITLE
Add support for Kopitiam card

### ISSUE THREAD

**Issue by zhongfu** [codebutler/farebot#61]
Kopitiam, a foodcourt in Singapore, offers a MiFare Classic card used to pay for meals with discounts. The balance stored in it appears to be in Sector 2. In the NXP TagInfo app:
```
Sector 2 (0x02)
[08] rwi  00 00 39 97 AE 00 00 21 78 59 00 00 00 00 00 20 |..9....!xY..... |
[09] rwi  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
[0A] rwi  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
[0B] wxx  A0:A1:A2:A3:A4:A5 FF:07:80 69 B0:B1:B2:B3:B4:B5
          MAD access key                (unknown key) (readable)
```
where "39 97" is the card's balance ($39.97), and "21 78" is the amount spent ($21.78)

Maybe support could be added in farebot?

**Comment by heru762004** [comment]
Now they are not reading from sector 2 anymore. I'm wondering, which sector they stored the kopitiam card balance and what is the key...

**Comment by zhongfu** [comment]
This seems to be impossible now unless we get access to the keys for sectors 0 and 1 to see if the balance is stored there -- as @heru762004 mentioned, the balance now is no longer stored in sector 2, and if you use an old Kopitiam card, the old values for balance and amount spent in sector 2 will stay the same.
