### ISSUE TITLE
Clipper card refill appears as "Unknown (0x248)"

### ISSUE THREAD

**Issue by Daniel15** [codebutler/farebot#65]
I got a Clipper card and put credit on it at the information desk at San Francisco airport. This refill appears as "Unknown (0x248)" in Farebot. On the Clipper website it appears as "Cash payment at a TOT, TRU or AVM".

**Comment by codebutler** [comment]
Please install the latest version from Google Play and re-open this ticket if you're still seeing this issue. Thanks!
