### ISSUE TITLE
Add preference to not launch app when card detected

### ISSUE THREAD

**Issue by haldean** [codebutler/farebot#73]
I really like the app, but I'd like a way to only scan a card when the app is already open; I have a [CardNinja wallet](http://www4.pcmag.com/media/images/373914-cardninja.jpg?thumb=y), so my Clipper card is stuck to the back of my phone, and every time I unlock the phone it launches the app. It'd be nice to have a way to only scan the card when the app is open.

I'm actually happy to implement this, but I wanted to confirm that you'd be okay with pulling it into mainline if I did before I start. Thanks!

**Comment by codebutler** [comment]
This will be in the upcoming version.
