### ISSUE TITLE
Australian Transport Card - Myki (Victoria) support

### ISSUE THREAD

**Issue by suniloz** [codebutler/farebot#9]
I'm attempting to add support for Myki public transport card. 

http://en.wikipedia.org/wiki/Myki

Its been listed as a MIFARE DESFire card.

**Comment by micolous** [comment]
Feel free to send me annotated data dumps (ie: what you last did, the balance, and value of the transaction). I've done some work on this and found some information is available in the "open" sectors.

I do not live in Melbourne, so have made limited progress with my own Myki card.  I've managed to pull most of the card number (except last digit) from the open sectors.

**Comment by micolous** [comment]
Sorry for the spam there -- this is a problem with rebasing your work all the time.

I pretty much abandoned my efforts after getting the card number only.  There is a third-party program called mykiplus which works by screen scraping the Myki website -- something which I don't think is an acceptable solution.  If you're interested in the code I wrote: https://github.com/micolous/farebot/pull/7

I'm going to pull this into the next release in my fork of Farebot.
