### ISSUE TITLE
Unknown Card for CEPAS card

### ISSUE THREAD

**Issue by cewei** [codebutler/farebot#90]
Having unknown card error with a number of CEPAS card. Attached is the export from the scan.

<?xml version="1.0" encoding="UTF-8"?><card type="3" id="081a6737" scanned_at="1416371365855">
 <purses>
   <purse id="0" valid="false" error="File 0 was an invalid file."/>
   <purse id="1" valid="false" error="File 1 was an invalid file."/>
   <purse id="2" valid="false" error="File 2 was an invalid file."/>
   <purse id="3" valid="false" error="File 3 was an invalid file."/>
   <purse id="4" valid="false" error="File 4 was an invalid file."/>
   <purse id="5" valid="false" error="File 5 was an invalid file."/>
   <purse id="6" valid="false" error="File 6 was an invalid file."/>
   <purse id="7" valid="false" error="File 7 was an invalid file."/>
   <purse id="8" valid="false" error="File 8 was an invalid file."/>
   <purse id="9" valid="false" error="File 9 was an invalid file."/>
   <purse id="10" valid="false" error="File 10 was an invalid file."/>
   <purse id="11" valid="false" error="File 11 was an invalid file."/>
   <purse id="12" valid="false" error="File 12 was an invalid file."/>
   <purse id="13" valid="false" error="File 13 was an invalid file."/>
   <purse id="14" valid="false" error="File 14 was an invalid file."/>
   <purse id="15" valid="false" error="File 15 was an invalid file."/>
 </purses>
 <histories>
   <history id="0" valid="false" error=""/>
   <history id="1" valid="false" error=""/>
   <history id="2" valid="false" error=""/>
   <history id="3" valid="false" error=""/>
   <history id="4" valid="false" error=""/>
   <history id="5" valid="false" error=""/>
   <history id="6" valid="false" error=""/>
   <history id="7" valid="false" error=""/>
   <history id="8" valid="false" error=""/>
   <history id="9" valid="false" error=""/>
   <history id="10" valid="false" error=""/>
   <history id="11" valid="false" error=""/>
   <history id="12" valid="false" error=""/>
   <history id="13" valid="false" error=""/>
   <history id="14" valid="false" error=""/>
   <history id="15" valid="false" error=""/>
 </histories>
</card>

**Comment by codebutler** [comment]
Please re-open this ticket if you're able to attach an export using the latest version on Google Play.
