### ISSUE TITLE
Unknown (0x1b) for San Francisco Bay Ferry Vallejo route

### ISSUE THREAD

**Issue by loganbruns** [codebutler/farebot#91]
Here is the website for the route:

http://sanfranciscobayferry.com/route/vallejo/sffb

Entry and exit from Vallejo or SF all show up as Unknown (0x1b)

**Comment by bdwyer2** [comment]
Looks like dec03e2 fixed this.

**Comment by codebutler** [comment]
Please install the latest version from Google Play and re-open this ticket if ferries still don't look right. Thanks!
