### ISSUE TITLE
Unknown (0x9) for Route 200 Bus (vallejo <> sf ferry backup bus route)

### ISSUE THREAD

**Issue by loganbruns** [codebutler/farebot#92]
Here is the website for the route (scroll down past the ferry part to the bus section):

http://sanfranciscobayferry.com/route/vallejo/sffb

Entry from Vallejo show up as Unknown (0x9)

**Comment by codebutler** [comment]
I'm going through and closing out old issues. Please re-open if this is still happening with the latest version. If possible please attach a screenshot and an export of the card data.
