### ISSUE TITLE
Potential library suggestion

### ISSUE THREAD

**Issue by stevelacy** [codebutler/farebot#95]
Just a suggestion, I would like to see a full NFC library with the cards supported in this project for usage elsewhere.

It would enable me to add nfc.Clipper.Routes (etc) to another project without needing to find and copy the classes/methods over manually.

**Comment by codebutler** [comment]
I've done a bunch of work recently to split the app up into multiple modules which would make this much easier.

Please note that the license requires that your application also be GPL if you use any FareBot code.
