### ISSUE TITLE
Error:Could not find runProguard on com.android.build.gradle.internal.api.ReadOnlyBuildType@5ef8949e

### ISSUE THREAD

**Issue by wizcalil** [codebutler/farebot#99]
Cant solve this error when i imported the project in Android studio

**Comment by pat2man** [comment]
I had this issue in another project. The solution was to upgrade Crashlytics.

**Comment by citizenconn** [comment]
I was able to get around that by changing the crashlytics classpath in the buildscript dependencies to:

`com.crashlytics.tools.gradle:crashlytics-gradle:1.+`

**Comment by wizcalil** [comment]
Thank you

**Comment by xsmaster** [comment]
Thank you so much! This was the resolution to my issue.

**Comment by codebutler** [comment]
Dependencies have been updated in master.
